language: java

services:
 - docker

before_install:
 - docker build -t=ci .

script:
 - docker container run -v $(pwd)/build:/JavaSingleValue/build ci

after_success:
 - bash <(curl -s https://codecov.io/bash)
